# Generated by Django 6.0.6 on 2026-06-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_suggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
