# Generated by Django 6.0.6 on 2026-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='resolved',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
